package com.savan.resumeportal.models;

import javax.persistence.*;

@Entity
@Table(name = "User") //Maps the User Entities to a table called User
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO) // Tells JPA to create a ID with an autogenerated unique value for the Entity
    private int id;
    private String userName;
    private String password;
    private boolean active;  //The user needs to be active at the time of login for Spring Security to check he active status
    private String roles; // Access roles such as admin access, user access

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getRoles() {
        return roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }
}
